# Basic
title: Rnthking Luo
subtitle: Stay hungry, Stay foolish
welcome_message: 欢迎大家来到我的博客，希望能和大家一起交流分享！:）
description: 嗨，我是罗伟广( Rnthking ), 目前居成都, 现在和身边的开发者朋友创办了一家软件公司，如果需要软件服务，可以联系我们哈 ! :)
creator: <a href="http://onevcat.com">@Rnthking基于喵神【王魏】源码修改</a>

url: "http://www.rnthking.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'https://rnthking.com'}
    - {title: 关于, description: 了解更多关于我, url: 'http://rnthking.com'}
    - {title: 订阅, description: 邮件订阅本站, url: '//store.objccn.io/subscribe'}

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "page/:num/"

# Comment
comment:
    disqus: onevcat
    # duoshuo:
# Social
social:
    weibo: 3591355593/Ffh9Q7oz1?ref=feedsdk&type=comment#_rnd1501744345788
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: rnthking@gmail.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: www.rnthking.com


# Serving
detach:  false
port:    80
host:    162.243.159.189
baseurl: "" # does not include hostname
show_dir_listing: false